### ISSUE TITLE
Filter index reads by quality score

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/barcodecop#1]
Motivated by https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3217-x

> We observed rates of cross-talk averaging 0.24 % when multiplexing 14 different samples with unique i5 and i7 index sequences. This cross-talk rate corresponded to 254,632 misassigned reads on a single lane of the Illumina HiSeq 2500. Notably, all types of misassignment occur at similar rates: incorrect i5, incorrect i7, and incorrect sequence reads. We demonstrate that misassignments can be nearly eliminated by quality filtering of index reads while preserving about 90 % of the original sequences.

**Comment by tholland** [comment]
Some other notes here: 
We need an output for quality score for the barcodes.  In addition, the filtering should throw out the reads if either index qual score is below the threshold.

**Comment by nhoffman** [comment]
@tholland - can you have a look at my updates to your branch and see if I've overlooked anything? I made some changes that should (in principle) make it a bit faster, though I didn't compare.

**Comment by nhoffman** [comment]
I think that we can leave the description of barcode quality statistics to another tool, or at least another issue.

**Comment by tholland** [comment]
Sounds good.  I don't see other changes that need to be made.

**Comment by nhoffman** [comment]
@tholland - merged. Thanks for your help!
