### ISSUE TITLE
Add cli argument to propagate 'allow-empty' boolean option to fastqlite

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/barcodecop#13]
[This change](https://github.com/nhoffman/fastalite/pull/6) to the fastalite package introduces an optional argument to `fastalite.fastqlite` to 'allow_empty' sequence and quality values, for instance as may occur in an adaptor trimmed fastq.

**Comment by nhoffman** [comment]
merged, thanks @dhoogest
